### ISSUE TITLE
[BUG]: Host buffer is not cleared when all particles are reset, causing flickering

### ISSUE THREAD

**Issue by Cubature1** [gelly-gmod/gelly#35]
### GPU

RTX 3050

### Operating System

Win 11

### Is this specific to performance?

- [ ] Yes
- [X] No

### Issue Type

None

### Incident Description

(Only observed on gm_construct) (May be exclusive to the unfinished drywall room) While spawning particles, random rings and orbs of liquid appear in the field of view.
![image](https://github.com/yogwoggf/gelly/assets/64175394/63802748-56d6-4a3d-be7e-15e71964d7b8)
Best screenshot I could get^

**Comment by yogwoggf** [comment]
Hmm, this issue is particularly difficult to triage as my own investigation proved to be a dead-end as this is actually an error with FleX's laplacian smoothing kernels. A quick spike of this issue made a build of Gelly where the host buffers are all cleared, and the renderer uses the raw positions--which solved the issue. However, the raw positions are terrible for rendering, but when using the smoothed positions, the issue comes back.

I'm not really sure what else to do, but given it has minimal impact, I may kick this to the backburner unfortunately

**Comment by yogwoggf** [comment]
Fixed in [1.21.4](https://github.com/gelly-gmod/gelly/releases/tag/1.21.4). The actual problem was that the simulation would randomly update in between frames, such that the renderer would be notified of _new_ particles when it wasn't actually ready to be rendered.
